### ISSUE TITLE
/etc/init.d/nginx: 1: /etc/init.d/nginx: N: not found

### ISSUE THREAD

**Issue by DJviolin** [JasonGiedymin/nginx-init-ubuntu#20]
I got this error message every time when I start a new nginx server and I don't know is it a problem or it's okay:

root@1abf1c2ef16c:/bin# sudo service nginx start
/etc/init.d/nginx: 1: /etc/init.d/nginx: N: not found
 * Starting Nginx Server...                                                                                   [ OK ]

root@1abf1c2ef16c:/bin#

I needed to modify the DAEMON value, because I installed the nginx binary in different place:

DAEMON=${DAEMON:-/usr/local/sbin/nginx} # path to daemon binary

And this is my report when I built Nginx from source:

Configuration summary
  + using system PCRE library
  + using system OpenSSL library
  + md5: using OpenSSL library
  + sha1: using OpenSSL library
  + using system zlib library

  nginx path prefix: "/usr/local/nginx"
  nginx binary file: "/usr/local/sbin"
  nginx configuration prefix: "/usr/local/nginx/conf"
  nginx configuration file: "/usr/local/nginx/conf/nginx.conf"
  nginx pid file: "/usr/local/nginx/logs/nginx.pid"
  nginx error log file: "/usr/local/nginx/logs/error.log"
  nginx http access log file: "/usr/local/nginx/logs/access.log"
  nginx http client request body temporary files: "client_body_temp"
  nginx http proxy temporary files: "proxy_temp"
  nginx http fastcgi temporary files: "fastcgi_temp"
  nginx http uwsgi temporary files: "uwsgi_temp"
  nginx http scgi temporary files: "scgi_temp"

**Comment by JasonGiedymin** [comment]
You should be able to set DAEMON to whatever you want.

For example:

```bash
$ export DAEMON=/home/nginxuser/bin/nginx
$ service nginx restart
```

The script should use what you set as DAEMON via the export above.
