### ISSUE TITLE
There is a typo in the doc.

### ISSUE THREAD

**Issue by tfarina** [JasonGiedymin/nginx-init-ubuntu#21]
One line says wget http://nginx.org/download/nginx-1.5.9.tar.gz while right after it, it says tar -xvf nginx-1.7.9.tar.gz.

I think you should just update the wget line to reference 1.7.9 instead.

**Comment by JasonGiedymin** [comment]
Your right, the docs are wrong! Sorry about that.

You want to do a pull request? Otherwise I'll get to it later tonight.

**Comment by tfarina** [comment]
No, sorry. I don't intend to send a pull request.

**Comment by NodexTech** [comment]
Still the same!

**Comment by JasonGiedymin** [comment]
Complete. See https://github.com/JasonGiedymin/nginx-init-ubuntu/releases/tag/v3.9.0
