### ISSUE TITLE
Get 502 on all sites after reload

### ISSUE THREAD

**Issue by krisquigley** [JasonGiedymin/nginx-init-ubuntu#24]
After running `reload` all sites display a 502 error and restarting the service does not work either.  I have to kill all the nginx workers and run `start` again to get nginx back up and running.

Any idea what may be causing this?

**Comment by JasonGiedymin** [comment]
Still happening? Reopen if so I'll try to find time and check.

**Comment by krisquigley** [comment]
Unfortunately, it is still happening.

**Comment by JasonGiedymin** [comment]
Provided is a vagrant file in this repo. Can you duplicate it with that vm? Mimic your config as much as possible.

-Jason
