### ISSUE TITLE
Variable description in your README.md

### ISSUE THREAD

**Issue by actuallymentor** [JasonGiedymin/nginx-init-ubuntu#25]
Great work, love it :)

The default values though are not self explanatory:

PATH
NGINXPATH
DAEMON
PS
PIDNAME
PIDFILE
PIDSPATH
DESCRIPTION
RUNAS
NGINX_CONF_FILE

I have no idea what the differences and connections are between PATH and NGINXPATH. Or for example PIDNAME, PIDFILE and PIDSPATH.

Where can I find these?

**Comment by JasonGiedymin** [comment]
Did you read the code and code comments?

The description is in it.

```shell
PS=${PS:-"nginx"}                             # process name
DESCRIPTION=${DESCRIPTION:-"Nginx Server..."} # process description
NGINXPATH=${NGINXPATH:-/usr/local/nginx}      # root path where installed
DAEMON=${DAEMON:-$NGINXPATH/sbin/nginx}       # path to daemon binary
NGINX_CONF_FILE=${NGINX_CONF_FILE:-$NGINXPATH/conf/nginx.conf} # config file path

PIDNAME=${PIDNAME:-"nginx"}                   # lets you do $PS-slave
PIDFILE=${PIDFILE:-$PIDNAME.pid}              # pid file
PIDSPATH=${PIDSPATH:-$NGINXPATH/logs}         # default pid location, you should change it
RUNAS=${RUNAS:-root}                          # user to run as
```

**Comment by JasonGiedymin** [comment]
If this is not enough I'll gladly take a pull request for documentation.

**Comment by actuallymentor** [comment]
Gladly, I made a local branch with updates. Haven't done  push requests before. How do we go from here?

**Comment by JasonGiedymin** [comment]
Go to pull request section of your repo and see if you can file a request that points toward this original parent repo.

https://help.github.com/articles/using-pull-requests/

**Comment by JasonGiedymin** [comment]
Also refer to this issue.

**Comment by actuallymentor** [comment]
Pull request created
